pipeline:
  name: Demo mine1
  identifier: Demo_mine
  projectIdentifier: Default_Project_1669441829842
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: acc_level_github
        repoName: xng-breadcrumb
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: lint
                  identifier: lint
                  spec:
                    shell: Sh
                    command: yarn install --frozen-lockfile --non-interactive
                  description: lint stage
