# https://github.com/zeke/semantic-pull-requests#configuration
titleOnly: true
scopes:
  - lib
  - e2e
  - docs
  - demo-app

types:
  - feat
  - fix
  - docs
  - style
  - refactor
  - perf
  - test
  - build
  - ci
  - chore
  - revert
allowEmptyScope: true
