import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'autoLabel'
})
export class AutoLabelPipe implements PipeTransform {
  transform(breadcrumbList: any, shouldautoGenerate: boolean, ...args: any[]): any {
    if (shouldautoGenerate) {
      return breadcrumbList;
    } else {
      return breadcrumbList.filter(breadcrumb => !breadcrumb.isAutoGeneratedLabel);
    }
    return null;
  }
}
